services:
  - type: web
    name: telegram-video-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    plan: free
    envVars:
      - key: PORT
        value: 8080
